name = "open-tech-lab-worker"
main = "src/workers/api.ts"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
workers_dev = false
route = { pattern = "api.open-tech-lab.dev/*", zone_name = "open-tech-lab.dev" }

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[[durable_objects.bindings]]
name = "SANDBOX"
class_name = "SandboxObject"
script_name = "open-tech-lab-worker"

[[migrations]]
tag = "v1"
new_classes = ["SandboxObject"]

[triggers]
crons = ["0 2 * * *"]
